

_target_: model_module.model.fullmodel.FullModel

voxel_pooling:
  # _target_: model_module.model.detection.voxel_pooling_module_16D.VoxelModule

  x_bound: [-51.2, 51.2, 0.8]
  y_bound: [-51.2, 51.2, 0.8]
  z_bound: [-5, 3, 8]
  d_bound: [2, 58, 0.5]
  final_dim: [256, 704]
  output_channels: 64
  downsample_factor : 4




backbone:
  _target_: model_module.model.backbones.aggregator.Agg16Agg4
  
  reduce_dim: 64
  # chs: [32, 56, 160, 448, 448, 448]
  chs: [160, 448, 448, 448]
  
  efficientnet: 
    _target_: model_module.model.backbones.efficientnet.EfficientNetExtractor
    
    layers: ['reduction_4', 'reduction_5']
    # layers: ['reduction_2', 'reduction_3', 'reduction_4', 'reduction_5']
    extra_layers: ['reduction_6', 'GAP']
    chs: ${model.backbone.chs}
    reduce_dim: ${model.backbone.reduce_dim}
    image_height: ${data.image.h}
    image_width: ${data.image.w}


seg_extractor:
  _target_: model_module.model.segmentation.semantic_feature_extractor.SemanticFeatureExtractor
  embed_dims: ${model.backbone.reduce_dim}
  n_head: 4
  q_size: 16          #! caution
  full_q_size: 128    #! caution


seg_head:
  _target_: model_module.model.segmentation.semantic_head.SemanticHead
  dim: ${model.backbone.reduce_dim}
  num_cls: 4