

_target_: model_module.model.fullmodel_pe.FullModel


backbone:
  _target_: model_module.model.backbones.aggregator.BB32
  
  efficientnet: 
    _target_: model_module.model.backbones.efficientnet.EfficientNetExtractor
    
    layers: ['reduction_5']
    chs: [272]
    reduce_dim: 64
    image_height: ${data.image.h}
    image_width: ${data.image.w}


seg_extractor:
  _target_: model_module.model.segmentation.semantic_feature_extractor_pe_cvt.SemanticFeatureExtractor
  b_res: 32
  image_height: ${data.image.h}
  image_width: ${data.image.w}
  bev_embedding: 
    bev_height: ${data.bev.h}
    bev_width: ${data.bev.w}
    h_meters: ${data.bev.h_meters}
    w_meters: ${data.bev.w_meters}
    offset: ${data.bev.offset}
    resolution: 8

  embed_dims: ${model.backbone.efficientnet.reduce_dim}
  n_head: 4
  q_size: 25          #! caution
  full_q_size: 100    #! caution


seg_head:
  _target_: model_module.model.segmentation.semantic_head.SemanticHead
  output: ${model.outputs}
  dim: ${model.backbone.efficientnet.reduce_dim}
#   num_cls: 2

# outputs:
#   bev: [0, 1]
#   center: [1, 2]