

road_iou:
  _target_: model_module.metrics.IoUMetric
  class_idx: 0
  label_indices: [[0,1]]

lane_iou:
  _target_: model_module.metrics.IoUMetric
  class_idx: 1
  label_indices: [[2,3]]


vehicle_iou:
  _target_: model_module.metrics.IoUMetric
  class_idx: 2
  label_indices: [[4, 5, 6, 7, 8, 10, 11]]
  min_visibility: 2