# iou:
#   _target_: model_module.metrics.IoUMetric
#   label_indices: [[4, 5, 6, 7, 8, 10, 11]]
#   min_visibility: 2

# iou_with_occlusions:
#   _target_: model_module.metrics.IoUMetric
#   label_indices: [[4, 5, 6, 7, 8, 10, 11]]