
defaults:
  - _self_
  - model: default_model
  - data: nuscenes_det
  # - loss: default_loss
  # - metrics: default_metrics


experiment:
  project: 3D_OD_For_Autonomous_Driving
  name: base
  uuid: ${now:%m%d_%H%M%S}
  save_dir: ${hydra:runtime.cwd}/logs/                # log directory, will be created
  

  seed: 2022
  checkpoint_interval: 1000
  log_image_interval: 500


loader:
  batch_size: 8         # per gpu
  num_workers: 4
  pin_memory: True
  prefetch_factor: 4


# AdamW
optimizer:
  weight_decay: 1e-7
  dual_lr: False
  lr: 1e-3
  # lr: 4e-3
  

# OneCycleLR
scheduler:
  name: onecycle
  div_factor: 10           # starts at lr / 10
  pct_start: 0.3           # reaches lr at 30% of total steps
  final_div_factor: 10     # ends at lr / 10 / 10
  # total_epochs: ${trainer.max_epochs}
  # total_steps: ${trainer.max_steps}
  cycle_momentum: False


# lightning trainer
trainer:
  # max_epochs: 24
  # max_steps: 30765  #! batch_size 2: 123060
  log_every_n_steps: 50

  gpus: 4
  precision: 32

  limit_train_batches: 1.0
  limit_val_batches: 1.0
  check_val_every_n_epoch: 1
  val_check_interval: 1.0
  num_sanity_val_steps: 0
  gradient_clip_val: 5.0
  sync_batchnorm: True  #! False