visible_weight: 1.0
visible:
  _target_: bev_transformer.losses.BinarySegmentationLoss

  label_indices: [[4, 5, 6, 7, 8, 10, 11]]
  gamma: 2.0
  alpha: -1.0
  min_visibility: 2

center_weight: 0.1
center:
  _target_: bev_transformer.losses.CenterLoss

  gamma: 2.0
  min_visibility: 2