visible_weight: 1.0
visible:
  _target_: model_module.losses.BinarySegmentationLoss_1ch

  label_indices: [[4, 5, 6, 7, 8, 10, 11]]
  gamma: 2.0
  alpha: -1.0
  min_visibility: 2

center_weight: 0.1
center:
  _target_: model_module.losses.CenterLoss

  gamma: 2.0
  min_visibility: 2

depth_weight: 0.05
depth:
  _target_: model_module.losses.DepthBCELoss

seg_weight: 0.1
seg:
  _target_: model_module.losses.SegmentationLoss

detection_weight: 0.005
detection:
  _target_: model_module.model.segmentation.losses.bipartiteMatchingLoss

  loss_cls :
    type : 'FocalLoss'
    use_sigmoid: True
    gamma : 2.0
    alpha : 0.5
    loss_weight : 2.0
  loss_bbox :
    type : 'L1Loss'
    loss_weight : 0.25
  loss_iou :
    type : 'GIoULoss'
    loss_weight : 0.0
  assigner :
    type : 'HungarianAssigner3D'
    cls_cost :
      type : 'FocalLossCost'
      weight : 2.0
    reg_cost :
      type : 'BBox3DL1Cost'
      weight : 0.25
    iou_cost :
      type : 'IoUCost'
      weight : 0.0
    pc_range : [-50.0,-50.0,-5.0, 50.0, 50.0, 3.0]
  sampler :
    type : 'PseudoSampler'
  bbox_coder:
    type : 'NMSFreeCoder'
    post_center_range : [-61.2, -61.2, -10.0, 61.2, 61.2, 10.0]
    pc_range : [-50.0,-50.0,-5.0, 50.0, 50.0, 3.0]
    max_num : 300
    voxel_size : [0.2, 0.2, 8]
    num_classes : 10
  
  