

vehicle_weight: 1.0
vehicle:
  _target_: model_module.losses.BinarySegmentationLoss

  class_idx: 0
  label_indices: [[4, 5, 6, 7, 8, 10, 11]]
  gamma: 2.0
  alpha: -1.0
  min_visibility: 2

# for center
center_weight: 0.1
center:
  _target_: model_module.losses.CenterLoss

  class_idx: 1
  gamma: 2.0
  min_visibility: 2